-- Consolidated Reports Migration
-- Run this entire script to set up the reports system fully.

-- 1. Create Table (if not exists)
CREATE TABLE IF NOT EXISTS public.reports (
    id bigint generated by default as identity primary key,
    reporter_id uuid references public.profiles(id) on delete cascade not null,
    reported_id uuid references public.profiles(id) on delete cascade, -- Nullable now to allow pet reports
    reason text not null, 
    description text,
    status text default 'pending', 
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Add Pets Column (if not exists)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reports' AND column_name = 'reported_pet_id') THEN
        ALTER TABLE public.reports ADD COLUMN reported_pet_id bigint REFERENCES public.pets(id) ON DELETE CASCADE;
    END IF;
END $$;

-- 3. Enable RLS
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- 4. Policies (Drop first to avoid duplicates)
DROP POLICY IF EXISTS "Users can create reports" ON public.reports;
DROP POLICY IF EXISTS "Admins can view all reports" ON public.reports;
DROP POLICY IF EXISTS "Admins can update reports" ON public.reports;
DROP POLICY IF EXISTS "Admins can delete reports" ON public.reports;

CREATE POLICY "Users can create reports" 
ON public.reports FOR INSERT 
WITH CHECK ( auth.uid() = reporter_id );

CREATE POLICY "Admins can view all reports" 
ON public.reports FOR SELECT 
USING ( (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' );

CREATE POLICY "Admins can update reports" 
ON public.reports FOR UPDATE 
USING ( (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' );

CREATE POLICY "Admins can delete reports" 
ON public.reports FOR DELETE 
USING ( (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' );
