-- 1. Create Interactions Table (Signal Collection)
CREATE TABLE IF NOT EXISTS public.interactions (
    id bigint generated by default as identity primary key,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    pet_id bigint REFERENCES public.pets(id) ON DELETE CASCADE NOT NULL,
    interaction_type text NOT NULL CHECK (interaction_type IN ('like', 'save', 'swipe_right', 'swipe_left', 'apply', 'share', 'view', 'dwell')),
    weight int DEFAULT 0,
    duration int DEFAULT 0, -- in seconds (for dwell)
    meta jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_interactions_user_pet ON public.interactions(user_id, pet_id);
CREATE INDEX IF NOT EXISTS idx_interactions_created_at ON public.interactions(created_at);

-- RLS
ALTER TABLE public.interactions ENABLE ROW LEVEL SECURITY;

-- Drop policies if they exist to allow re-running the migration
DROP POLICY IF EXISTS "Users can insert their own interactions" ON public.interactions;
CREATE POLICY "Users can insert their own interactions" ON public.interactions
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own interactions" ON public.interactions;
CREATE POLICY "Users can view their own interactions" ON public.interactions
    FOR SELECT USING (auth.uid() = user_id);

-- 2. Scored Recommendations RPC
-- This function calculates a match score on the fly
CREATE OR REPLACE FUNCTION get_match_recommendations(
    p_user_id uuid,
    p_limit int DEFAULT 20,
    p_offset int DEFAULT 0,
    p_filters jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE (
    id bigint,
    name text, 
    breed text,
    age text,
    image text,
    distance text,
    match_score float,
    owner_id uuid, -- Added owner_id return
    owner_profile jsonb -- Added owner_profile return
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_lat float;
    v_lng float;
    v_preferred_breeds text[];
    v_interacted_pet_ids bigint[];
BEGIN
    -- 1. Get User Location (if available)
    SELECT latitude, longitude INTO v_lat, v_lng
    FROM public.profiles
    WHERE public.profiles.id = p_user_id;

    -- 2. Get negative interaction IDs (to exclude)
    SELECT array_agg(pet_id) INTO v_interacted_pet_ids
    FROM public.interactions
    WHERE user_id = p_user_id 
    AND interaction_type IN ('swipe_left', 'like', 'save', 'apply'); -- Exclude already acted upon

    -- 3. Get User Preferences (Simplified: breeds they liked)
    SELECT array_agg(DISTINCT p.breed) INTO v_preferred_breeds
    FROM public.interactions i
    JOIN public.pets p ON p.id = i.pet_id
    WHERE i.user_id = p_user_id AND i.weight > 0;

    RETURN QUERY
    WITH scored_pets AS (
        SELECT 
            p.id,
            p.name,
            p.breed,
            p.age,
            p.image,
            p.distance, -- Stored string distance
            p.owner_id,
            -- Calculate Score
            (
                -- Base Score
                100 
                
                -- Recency Boost (Newer = User sees new stuff)
                + (CASE WHEN p.created_at > now() - interval '2 days' THEN 20 ELSE 0 END)
                
                -- Breed Match Boost
                + (CASE WHEN p.breed = ANY(v_preferred_breeds) THEN 30 ELSE 0 END)
                
                -- Signal: High Engagement (Popularity) - Simplified proxy
                + (p.likes * 2) 

                -- Random Factor for Serendipity (0-10)
                + (random() * 10)
            )::float as raw_score
        FROM public.pets p
        WHERE p.status = 'available'
        AND (v_interacted_pet_ids IS NULL OR p.id != ALL(v_interacted_pet_ids))
        AND p.owner_id != p_user_id -- Don't show own pets
        -- Apply Filters (Basic examples)
        AND (p_filters->>'type' IS NULL OR p_filters->>'type' = 'all' OR  p.breed ILIKE '%' || (p_filters->>'type') || '%') -- Very basic, needs proper type column ideally
    )
    SELECT 
        sp.id,
        sp.name,
        sp.breed,
        sp.age,
        sp.image,
        sp.distance,
        sp.raw_score as match_score,
        sp.owner_id,
        (SELECT row_to_json(pro) FROM public.profiles pro WHERE pro.id = sp.owner_id) as owner_profile
    FROM scored_pets sp
    ORDER BY sp.raw_score DESC
    LIMIT p_limit OFFSET p_offset;
END;
$$;
