-- 1. Add partner_pet_id to pets table (Represents exclusive relationship)
ALTER TABLE public.pets
ADD COLUMN partner_pet_id bigint REFERENCES public.pets(id) ON DELETE SET NULL;

-- 2. Create Dating Requests Table
CREATE TABLE public.dating_requests (
    id bigint generated by default as identity primary key,
    requester_pet_id bigint REFERENCES public.pets(id) ON DELETE CASCADE NOT NULL,
    target_pet_id bigint REFERENCES public.pets(id) ON DELETE CASCADE NOT NULL,
    status text NOT NULL CHECK (status IN ('pending', 'accepted', 'rejected')),
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. RLS Policies
ALTER TABLE public.dating_requests ENABLE ROW LEVEL SECURITY;

-- Policy: Users can see requests involving their pets
CREATE POLICY "Users can view requests for their pets" ON public.dating_requests
FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.pets WHERE id = dating_requests.requester_pet_id AND owner_id = auth.uid()) OR
    EXISTS (SELECT 1 FROM public.pets WHERE id = dating_requests.target_pet_id AND owner_id = auth.uid())
);

-- Policy: Users can insert requests FROM their pets
CREATE POLICY "Users can create requests from their pets" ON public.dating_requests
FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.pets WHERE id = dating_requests.requester_pet_id AND owner_id = auth.uid())
);

-- Policy: Users can update requests involving their pets (Accept/Reject)
CREATE POLICY "Users can update requests for their pets" ON public.dating_requests
FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.pets WHERE id = dating_requests.target_pet_id AND owner_id = auth.uid()) OR
    EXISTS (SELECT 1 FROM public.pets WHERE id = dating_requests.requester_pet_id AND owner_id = auth.uid())
);

-- 4. Indexes for performance
CREATE INDEX idx_dating_requests_target ON public.dating_requests(target_pet_id);
CREATE INDEX idx_dating_requests_requester ON public.dating_requests(requester_pet_id);
CREATE INDEX idx_pets_partner ON public.pets(partner_pet_id);
