-- Create analytics_events table
create table public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  session_id uuid not null,
  event_type text not null, -- 'page_view', 'click', 'scroll', 'session_start', 'heartbeat'
  payload jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.analytics_events enable row level security;

-- Policies
-- Users can insert their own events (authenticated)
create policy "Users can insert own analytics." on public.analytics_events
  for insert with check (auth.uid() = user_id);

-- Anon users can also insert (for public tracking if needed, usually restrictive but needed here for pre-login tracking)
-- Ideally this opens up spam risk, but for this demo/scale we allow anon insert with matching session_id logic if we enforce it elsewhere.
-- For simplicity, allow insert to public role for now so analytics work for visitors.
create policy "Anyone can insert analytics." on public.analytics_events
  for insert with check (true);

-- Only admins/service role can view analytics (usually)
-- keeping it private for now
create policy "No one can view analytics via API." on public.analytics_events
  for select using (false);
