-- Create Journey Milestones Table
create table public.journey_milestones (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  order_index int not null
);

-- RLS for Milestones
alter table public.journey_milestones enable row level security;
create policy "Milestones are viewable by everyone." on public.journey_milestones for select using (true);

-- Create User Journey Progress Table
create table public.user_journey_progress (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  milestone_slug text references public.journey_milestones(slug) on delete cascade not null,
  status text check (status in ('locked', 'available', 'completed', 'skipped')) default 'locked',
  completed_at timestamp with time zone,
  meta jsonb default '{}'::jsonb,
  unique(user_id, milestone_slug)
);

-- RLS for Progress
alter table public.user_journey_progress enable row level security;
create policy "Users can view their own progress." on public.user_journey_progress for select using (auth.uid() = user_id);
create policy "Users can update their own progress." on public.user_journey_progress for update using (auth.uid() = user_id);
create policy "Users can insert their own progress." on public.user_journey_progress for insert with check (auth.uid() = user_id);

-- Initial Seed Data
insert into public.journey_milestones (slug, title, description, order_index) values
('profile-complete', 'Profile Perfection', 'Complete your profile to look trustworthy to pet owners.', 1),
('first-like', 'Love at First Sight', 'Find a pet you love and give them a like.', 2),
('first-message', 'Break the Ice', 'Start a conversation with a pet owner.', 3),
('meet-scheduled', 'Meet & Greet', 'Schedule a time to meet your potential new family member.', 4)
on conflict (slug) do nothing;
