-- 1. LIKES
create table public.likes (
  user_id uuid references public.profiles(id) on delete cascade not null,
  pet_id bigint references public.pets(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  primary key (user_id, pet_id)
);
alter table public.likes enable row level security;
create policy "Users can view their own likes." on public.likes for select using (auth.uid() = user_id);
create policy "Users can insert their own likes." on public.likes for insert with check (auth.uid() = user_id);
create policy "Users can delete their own likes." on public.likes for delete using (auth.uid() = user_id);

-- 2. MATCHES
create table public.matches (
  user_id uuid references public.profiles(id) on delete cascade not null,
  pet_id bigint references public.pets(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  primary key (user_id, pet_id)
);
alter table public.matches enable row level security;
create policy "Users can view their own matches." on public.matches for select using (auth.uid() = user_id);
create policy "Users can insert their own matches." on public.matches for insert with check (auth.uid() = user_id);
create policy "Users can delete their own matches." on public.matches for delete using (auth.uid() = user_id);

-- 3. COLLECTIONS
create table public.collections (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.collections enable row level security;
create policy "Users can view their own collections." on public.collections for select using (auth.uid() = user_id);
create policy "Users can insert their own collections." on public.collections for insert with check (auth.uid() = user_id);
create policy "Users can delete their own collections." on public.collections for delete using (auth.uid() = user_id);

-- 4. COLLECTION ITEMS
create table public.collection_items (
  collection_id bigint references public.collections(id) on delete cascade not null,
  pet_id bigint references public.pets(id) on delete cascade not null,
  added_at timestamp with time zone default timezone('utc'::text, now()),
  primary key (collection_id, pet_id)
);
alter table public.collection_items enable row level security;
create policy "Users can view items in their collections." on public.collection_items for select using (
  exists (select 1 from public.collections c where c.id = collection_items.collection_id and c.user_id = auth.uid())
);
create policy "Users can add items to their collections." on public.collection_items for insert with check (
  exists (select 1 from public.collections c where c.id = collection_items.collection_id and c.user_id = auth.uid())
);
create policy "Users can remove items from their collections." on public.collection_items for delete using (
  exists (select 1 from public.collections c where c.id = collection_items.collection_id and c.user_id = auth.uid())
);
