-- Create Feedback Table
create table if not exists public.feedback (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users(id),
    rating integer not null check (rating >= 1 and rating <= 5),
    category text not null,
    description text not null
);

-- Enable RLS
alter table public.feedback enable row level security;

-- Policies

-- 1. Allow authenticated users to insert feedback
create policy "Users can insert their own feedback"
on public.feedback for insert
to authenticated
with check (true);

-- 2. Allow users to view their own feedback (optional, but good practice)
create policy "Users can view their own feedback"
on public.feedback for select
to authenticated
using (auth.uid() = user_id);

-- 3. Allow admins/service role to view all (Supabase service role bypasses RLS by default, but good to be explicit for app admin implementation later)
-- For now, we rely on Dashboard access or specific admin role check if you have one.
