-- Create Reports Table
CREATE TABLE public.reports (
    id bigint generated by default as identity primary key,
    reporter_id uuid references public.profiles(id) on delete cascade not null,
    reported_id uuid references public.profiles(id) on delete cascade not null,
    reason text not null, -- 'spam', 'harassment', 'inappropriate', 'other'
    description text,
    status text default 'pending', -- 'pending', 'resolved', 'dismissed'
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can create reports" 
ON public.reports FOR INSERT 
WITH CHECK ( auth.uid() = reporter_id );

CREATE POLICY "Admins can view all reports" 
ON public.reports FOR SELECT 
USING ( (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' );

CREATE POLICY "Admins can update reports" 
ON public.reports FOR UPDATE 
USING ( (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' );

CREATE POLICY "Admins can delete reports" 
ON public.reports FOR DELETE 
USING ( (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' );
