-- Enable RLS
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- 1. PROFILES (Extends Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  username text unique,
  avatar_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);

-- 2. PETS
create table public.pets (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) on delete cascade not null,
  name text not null,
  breed text,
  age text,
  gender text,
  image text,
  images text[], -- Array of strings
  bio text,
  traits text[],
  distance text default '1m',
  likes bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table public.pets enable row level security;
create policy "Pets are viewable by everyone." on public.pets for select using (true);
create policy "Users can insert their own pets." on public.pets for insert with check (auth.uid() = owner_id);
create policy "Users can update own pets." on public.pets for update using (auth.uid() = owner_id);

-- 3. CHAT CONVERSATIONS
create table public.conversations (
  id bigint generated by default as identity primary key,
  participant_a uuid references public.profiles(id) on delete cascade not null,
  participant_b uuid references public.profiles(id) on delete cascade not null,
  pet_id bigint references public.pets(id) on delete set null, -- Optional context
  last_message text,
  last_message_time timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(participant_a, participant_b, pet_id)
);
alter table public.conversations enable row level security;
create policy "Users can view their conversations." on public.conversations for select using (auth.uid() = participant_a or auth.uid() = participant_b);
create policy "Users can create conversations." on public.conversations for insert with check (auth.uid() = participant_a OR auth.uid() = participant_b);
create policy "Users can update their conversations." on public.conversations for update using (auth.uid() = participant_a or auth.uid() = participant_b);

-- 4. MESSAGES
create table public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references public.conversations(id) on delete cascade not null,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  text text not null,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  read boolean default false
);
alter table public.messages enable row level security;
create policy "Users can view messages in their conversations." on public.messages for select using (
  exists (
    select 1 from public.conversations c 
    where c.id = messages.conversation_id 
    and (c.participant_a = auth.uid() or c.participant_b = auth.uid())
  )
);
create policy "Users can insert messages in their conversations." on public.messages for insert with check (
  auth.uid() = sender_id
);

-- Realtime subscriptions
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.pets;
